# Generated by Django 3.2.5 on 2022-03-03 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserRoles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("role_type", models.CharField(max_length=250, unique=True)),
                (
                    "role_description",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("upload", models.BooleanField(default=False)),
                ("human_feedback_loop", models.BooleanField(default=False)),
                ("share_mom", models.BooleanField(default=False)),
                ("dashboard", models.BooleanField(default=False)),
                ("configuration", models.BooleanField(default=False)),
                ("qc", models.BooleanField(default=False)),
                ("home_screen", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "api_roles",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="CustomUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=100, unique=True, verbose_name="email address"
                    ),
                ),
                ("authorize_timestamp", models.DateTimeField(auto_now_add=True)),
                ("modified", models.DateField(null=True)),
                ("comments", models.CharField(blank=True, max_length=250, null=True)),
                ("is_active", models.BooleanField(default=True)),
                (
                    "role",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="authorize.userroles",
                    ),
                ),
                (
                    "team",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="users",
                        to="rest_api.team",
                    ),
                ),
            ],
            options={
                "db_table": "api_customuser",
                "ordering": ["-id"],
            },
        ),
    ]
