# Generated by Django 3.2.5 on 2022-03-09 07:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("authorize", "0002_rename_human_feedback_loop_userroles_mom"),
    ]

    operations = [
        migrations.AddField(
            model_name="customuser",
            name="name",
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
