import { makeStyles } from "@material-ui/core/styles";

const useStyles = makeStyles((theme) => ({
    TeamsConfiguration: {
        fontSize: "24px",
        fontWeight: "500",
    },
    SearchBase: {
        border: "solid 1px #eaeaea",
        boxShadow: "0 2px 4px 0 rgba(0, 0, 0, 0.08)",
        width: "360px",
        height: "35px",
        display: "flex",
        backgroundColor: theme.palette.white.main,
        margin: "5px",
    },
    menuWidth: {
        "& .MuiPaper-root": {
            overflow: "visible",
            border: "1px solid rgba(0, 0, 0, 0.08)",
            borderRadius: "16px",
        },
        "& .MuiMenu-list": {
            height: "220px",
            width: "550px",
            padding: "10px",
            margin: "2px",
        },
    },
    filterbtn: {
        background: theme.palette.white.main,
        border: "none",
        height: "40px",
        marginLeft: "10px",
        width: "100px",
        fontSize: "14px",
        fontWeight: "bold",
    },
    select: {
        fontSize: "14px",
        fontWeight: "bold",
        paddingRight: "5px",
        borderRadius: "20px",
        width: "250px",
    },
    headerButtons: {
        textTransform: "none",
        maxWidth: "150px",
        height: "30px",
        fontSize: "16px",
        border: "none",
        margin: "2px 0 0 5px",
        marginLeft: "15px",
    },
    TeamCount: {
        fontWeight: "bold",
        borderRight: `1px solid ${theme.palette.grey.secondary}`,
        padding: "5px 10px 10px 0px",
    },
    SubmitButton: {
        textTransform: "none",
        minWidth: "150px",
        fontSize: "14px",
        fontWeight: "bold",
        borderRadius: "8px",
    },
    ResetButton: {
        textTransform: "none",
        minWidth: "200px",
        fontSize: "14px",
        fontWeight: "bold",
        color: theme.palette.primary.main,
        backgroundColor: theme.palette.white.main,
        justifyContent: "flex-start",
    },
    LabelMargin: {
        marginBottom: "5px",
        fontWeight: "bold",
        fontSize: "14px",
    },
    MainContent: {
        width: "100%",
        minHeight: "85vh",
        borderRadius: "16px",
    },
    ActualContent: {
        display: "flex",
        flexDirection: "column",
        justifyContent: "center",
        alignItems: "center",
        minHeight: "70vh",
    },
    TeamName: {
        fontWeight: "bold",
        fontSize: "18px",
        marginBottom: "0px",
        color: theme.palette.dark.main,
    },
    Members: {
        fontSize: "14px",
        color: theme.palette.dark.main,
        fontFamily: "Lato",
    },
    CreatedOn: {
        fontSize: "12px",
        color: theme.palette.dark.main,
    },
    DetailHeader: {
        fontSize: "14px",
        color: theme.palette.dark.main,
        fontWeight: "bold",
        fontFamily: "Lato",
    },
    TeamListCard: {
        display: "flex",
        justifyContent: "space-between",
        alignItems: "center",
        padding: "15px",
        marginTop: "15px",
        boxShadow: "0 16px 32px 0 rgba(0, 0, 0, 0.1)",
        borderRadius: "16px",
        boxSizing: "border-box",
        "&:hover": {
            borderLeft: `16px solid ${theme.palette.primary.secondary}`,
            transition: "0.3s",
        },
    },
    TeamIconBox: {
        width: "80px",
        height: "80px",
        borderRadius: "50%",
        background: theme.palette.grey.tertiary,
    },
    EditButton: {
        color: theme.palette.primary.main,
        width: "145px",
        height: "30px",
        fontWeight: "bold",
        border: `2px solid ${theme.palette.primary.tertiary}`,
    },
    TeamCardPartition: {
        display: "flex",
        flexDirection: "column",
        alignItems: "flex-start",
        borderRight: `1px solid ${theme.palette.grey.secondary}`,
        paddingRight: "100px",
        marginLeft: "30px",
    },
    GridCardContainer: {
        display: "grid",
        gridTemplateColumns: "repeat(auto-fit, 294px)",
        rowGap: "1em",
        columnGap: "30px",
        justifyItems: "center",
    },
    TeamGridCard: {
        display: "flex",
        justifyContent: "flex-start",
        alignItems: "center",
        flexDirection: "column",
        boxShadow: "0 16px 32px 0 rgba(0, 0, 0, 0.1)",
        borderRadius: "16px",
        height: "420px",
        width: "294px",
        padding: "24.5px 0 22.5px 0",
        boxSizing: "border-box",
        "&:hover": {
            borderBottom: `16px solid ${theme.palette.primary.secondary}`,
            transition: "0.3s",
        },
    },
    TeamGridCardPartition: {
        display: "flex",
        flexDirection: "column",
        alignItems: "center",
        justifyContent: "center",
        width: "100%",
        marginBottom: "15px",
        padding: "0 0 15px 0",
        borderBottom: `1px solid ${theme.palette.grey.secondary}`,
    },
    Checkbox: {
        width: "18px",
        height: "18px",
        objectFit: "contain",
        marginRight: "10px !important",
        borderRadius: "16px !important",
    },
    CheckboxContainer: {
        margin: "25px 0 0 20px",
        opacity: "0.3",
        fontFamily: "lato",
    },
    TeamFormContainer: {
        paddingBottom: "30px",
        marginBottom: "30px",
        borderBottom: `1px solid ${theme.palette.grey.secondary}`,
    },
    SearchInputRoot: {
        border: "solid 1px #eaeaea",
        boxShadow: "0 2px 4px 0 rgba(0, 0, 0, 0.08) !important",
        width: "360px",
        height: "35px",
        display: "flex",
        backgroundColor: theme.palette.white.main,
        opacity: "0.5",
        borderRadius: "8px",
    },
    MoreOptions: {
        width: "200px",
        height: "112px",
        borderRadius: "16px",
        boxShadow: "0 16px 32px 0 rgba(0, 0, 0, 0.1)",
        border: "solid 1px rgba(0, 0, 0, 0.08)",
        backgroundColor: theme.palette.white.main,
    },
    CheckboxOpacity: {
        opacity: "1 !important",
    },
}));

export default useStyles;
