"""
Django settings for sense_maker project.

Generated by 'django-admin startproject' using Django 3.2.5.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

import logging
from pathlib import Path

import boto3

from boiler_plate.utility.constants import APP_CONFIG_PATH
from boiler_plate.utility.read_yaml import ReadYaml
from intake_endpoint import intake_endpoint

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# input_yaml = ReadYaml(BASE_DIR/ APP_CONFIG_PATH['input'])
# input_endpoint_params = input_yaml.get_applicable_input_config()

log_yaml = ReadYaml(BASE_DIR / APP_CONFIG_PATH["log"])
log_params = log_yaml.get_applicable_log_config()


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = "django-insecure-1)arhy!su1msgt0x5xs=5g-nndc&p-31r$cyvyp(hhhrg@gu(@"

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "corsheaders",
    "django_apscheduler",
    "rest_api.apps.RestApiConfig",
    "intake_endpoint.apps.IntakeEndpointConfig",
    "authorize.apps.OauthuserConfig",
    "output_endpoint.apps.OutputEndpointConfig",
]


MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "sense_maker.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "sense_maker.wsgi.application"


DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.mysql",
        "NAME": "momdev",
        "USER": "srcmomdev",
        "PASSWORD": "F3C#XPWm-E-#5wf9",
        "HOST": "aamsql-apm1008638-devcl02.cluster-ckkjwfxrnuox.us-east-1.rds.amazonaws.com",
        "PORT": "3306",
    }
}


# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_L10N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = "/static/"

MEDIA_URL = "/media/"
MEDIA_ROOT = intake_endpoint.get_applicable_config()["url"]

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "verbose": {
            "format": "{levelname} {asctime} {module} {process:d} {thread:d} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "file": {
            "level": log_params["level"],
            "class": log_params["class"],
            "filename": log_params["filename"],
            "formatter": "verbose",
        },
    },
    "loggers": {
        "file": {
            "handlers": ["file"],
            "level": log_params["level"],
            "propagate": log_params["propagate"],
        },
    },
}


AUTH_USER_MODEL = "authorize.CustomUser"  # Pratilipi custom user wrapper

PASSWORD_HASHERS = [
    "django.contrib.auth.hashers.PBKDF2PasswordHasher",
]

HOST = "http://localhost:3000"

CORS_ALLOWED_ORIGINS = [
    HOST,
]


# S3 Config
for name in logging.Logger.manager.loggerDict.keys():
    if ("boto" in name) or ("urllib3" in name):
        logging.getLogger(name).setLevel(logging.WARNING)

USE_S3 = True
AWS_STORAGE_BUCKET_NAME = "mom-bucket-uat"
