# Generated by Django 3.2.5 on 2022-03-25 10:18

from django.db import migrations, models

import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=250, upload_to=rest_api.models.upload_to
                    ),
                ),
                (
                    "masked_request_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("date", models.DateField(auto_now_add=True)),
                ("status", models.CharField(default="Uploaded", max_length=50)),
                ("file_size", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "api_file",
                "ordering": ["-id"],
                "managed": False,
            },
        ),
    ]
