# Generated by Django 3.2.5 on 2022-03-03 15:38

import django.db.models.deletion
from django.db import migrations, models

import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ConsolidateModelsData",
            fields=[
                (
                    "cns_data_id",
                    models.AutoField(primary_key=True, serialize=False, unique=True),
                ),
                ("file_id", models.CharField(blank=True, max_length=10, null=True)),
                ("team_id", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "participant_id",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("chunk_id", models.CharField(blank=True, max_length=10, null=True)),
                ("start_time", models.CharField(blank=True, max_length=10, null=True)),
                ("end_time", models.CharField(blank=True, max_length=10, null=True)),
                (
                    "audio_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                (
                    "video_path",
                    models.CharField(blank=True, max_length=1000, null=True),
                ),
                ("marker", models.CharField(blank=True, max_length=200, null=True)),
                ("label", models.CharField(blank=True, max_length=200, null=True)),
                ("events", models.CharField(blank=True, max_length=1000, null=True)),
                ("comments", models.CharField(blank=True, max_length=250, null=True)),
                ("cns_timestamp", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_consolidate",
            },
        ),
        migrations.CreateModel(
            name="FeedBackLoop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("request_id", models.CharField(blank=True, max_length=250)),
                (
                    "mom_output_v1",
                    models.FileField(
                        max_length=250, upload_to=rest_api.models.upload_to
                    ),
                ),
                (
                    "mom_output_v2",
                    models.FileField(
                        max_length=250, upload_to=rest_api.models.upload_to
                    ),
                ),
                ("is_mom_exist", models.BooleanField(default=False)),
            ],
            options={
                "db_table": "api_mom",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "file",
                    models.FileField(
                        max_length=250, upload_to=rest_api.models.upload_to
                    ),
                ),
                (
                    "masked_request_id",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("date", models.DateTimeField(auto_now=False, auto_now_add=True)),
                ("status", models.CharField(default="Uploaded", max_length=50)),
                ("file_size", models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                "db_table": "api_file",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="Team",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250, unique=True)),
                ("dl_email", models.CharField(max_length=250)),
                ("sme_name", models.CharField(max_length=250)),
                ("sme_email", models.CharField(max_length=250)),
                ("sme_email_notification", models.BooleanField(default=True)),
                ("po_name", models.CharField(max_length=250)),
                ("po_email", models.CharField(max_length=250)),
                ("po_email_notification", models.BooleanField(default=False)),
                ("manager_name", models.CharField(max_length=250)),
                ("manager_email", models.CharField(max_length=250)),
                ("manager_email_notification", models.BooleanField(default=False)),
                ("created_date", models.DateField(auto_now_add=True)),
            ],
            options={
                "db_table": "api_team",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="UserModel",
            fields=[
                ("user_id", models.IntegerField(primary_key=True, serialize=False)),
                ("user_name", models.CharField(max_length=100)),
                ("email", models.EmailField(max_length=254)),
                ("team_id", models.IntegerField()),
                ("role", models.CharField(max_length=50)),
            ],
            options={
                "db_table": "api_user",
            },
        ),
        migrations.CreateModel(
            name="TeamMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("email", models.CharField(max_length=250)),
                (
                    "team",
                    models.ManyToManyField(
                        related_name="team_members", to="rest_api.Team"
                    ),
                ),
            ],
            options={
                "db_table": "api_team_member",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="MeetingMetadata",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "project_name",
                    models.CharField(blank=True, max_length=250, null=True),
                ),
                ("mom_generation_date", models.DateField(blank=True, null=True)),
                ("organiser", models.CharField(blank=True, max_length=250, null=True)),
                ("location", models.CharField(blank=True, max_length=250, null=True)),
                (
                    "meeting_duration",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("attendees", models.CharField(max_length=1000, blank=True, null=True)),
                (
                    "meeting",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="metadata",
                        to="rest_api.file",
                    ),
                ),
            ],
            options={
                "db_table": "api_meeting_metadata",
                "ordering": ["-id"],
            },
        ),
        migrations.CreateModel(
            name="JiraTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("jira_issue_id", models.CharField(max_length=50)),
                ("jira_issue_key", models.CharField(max_length=250)),
                ("jira_issue_url", models.CharField(max_length=250)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("comments", models.CharField(blank=True, max_length=250, null=True)),
                ("status", models.BooleanField(default=True)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_transection",
                        to="rest_api.team",
                    ),
                ),
            ],
            options={
                "db_table": "api_jira_transaction",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
        migrations.CreateModel(
            name="JIRADetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ticket_no", models.CharField(max_length=250)),
                (
                    "team",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="jira_details",
                        to="rest_api.team",
                    ),
                ),
            ],
            options={
                "db_table": "api_jira_details",
                "ordering": ["-id"],
            },
        ),
        migrations.AddField(
            model_name="file",
            name="team_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="files",
                to="rest_api.team",
            ),
        ),
    ]
