# Generated by Django 3.2.5 on 2022-03-03 16:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="jiratransaction",
            name="team",
        ),
        migrations.AddField(
            model_name="jiratransaction",
            name="jira_detail_id",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="rest_api.jiradetails",
            ),
            preserve_default=False,
        ),
    ]
