# Generated by Django 3.2.5 on 2022-03-09 06:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("rest_api", "0003_rename_jira_detail_id_jiratransaction_jira_detail"),
    ]

    operations = [
        migrations.AddField(
            model_name="file",
            name="user",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.DO_NOTHING,
                related_name="files",
                to="authorize.customuser",
            ),
            preserve_default=False,
        ),
    ]
