# Generated by Django 3.2.5 on 2022-03-21 12:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("rest_api", "0004_file_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="MLModelStatus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=200)),
                ("status", models.BooleanField()),
                (
                    "file",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="rest_api.file"
                    ),
                ),
            ],
            options={
                "db_table": "api_ml_status",
                "ordering": ["-id"],
                "managed": True,
            },
        ),
    ]
