export const Upload = {
    UPLOAD_FILE: "UPLOAD_FILE",
    GET_UPLOADED_FILES: "GET_UPLOADED_FILES",
    CANCEL_FILE_UPLOAD: "CANCEL_FILE_UPLOAD",
    PROCESS_UPLOADED_FILE: "PROCESS_UPLOADED_FILE",
    CHANGE_FILE_STATUS: "CHANGE_FILE_STATUS",
    PROCESS_FILE_TRANSCRIPTION: "PROCESS_FILE_TRANSCRIPTION",
    PLAYBACK_FILE_URL: "PLAYBACK_FILE_URL",
    FRAMES_FILE_URL: "FRAMES_FILE_URL",
};
export const Mom = {
    GET_MOM: "GET_MOM",
    UPDATE_FEEDBACK: "UPDATE_FEEDBACK",
    GET_MEETING_METADATA: "GET_MEETING_METADATA",
    PATCH_MEETING_METADATA: "PATCH_MEETING_METADATA",
    GET_PDF_REPORT: "GET_PDF_REPORT",
};
export const ScrumTeamName = {
    GET_SCRUM_TEAM_NAME: "GET_SCRUM_TEAM_NAME",
    ADD_SCRUM_TEAM_NAME: "ADD_SCRUM_TEAM_NAME",
};
export const Login = {
    AUTHENTICATE_USER_LOGIN: "AUTHENTICATE_USER_LOGIN",
};
export const Summary = {
    GET_SUMMARY: "GET_SUMMARY",
    JIRA_POST: "JIRA_POST",
};
export const CommonResponse = {
    INIT: "INIT",
    SUCCESS: "SUCCESS",
    ERROR: "ERROR",
    PROMISEERROR: "PROMISEERROR",
};

export const Config = {
    GET_ALL_TEAMS: "GET_ALL_TEAMS",
    ADD_TEAM: "ADD_TEAM",
    DELETE_TEAM: "DELETE_TEAM",
    UPDATE_TEAM: "UPDATE_TEAM",
};

export const errorMessage = {
    COMMON_ERROR: "COMMON_ERROR",
};
