# Status Check specs
REST_API = "api"
STATUS = "status"
MODULE = "module"
COMPONENT = "component"
CRASHED_STATUS = "CRASHED"
COMPLETED_STATUS = "COMPLETED"
RESPONSE_PATH = "response_path"
IN_PROGRESS_STATUS = "IN_PROGRESS"
REQUEST_ID_KEY = "masked_request_id"
BACKEND_START_TIME = "backend_start_time"
BACKEND_TIME_FORMAT = "%Y-%m-%dT%H:%M:%S.%fZ"
