# Generated by Django 3.2.5 on 2021-10-06 10:59

from django.db import migrations, models
import django.db.models.deletion
import rest_api.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'api_team',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(max_length=250, upload_to=rest_api.models.upload_to)),
                ('masked_request_id', models.CharField(blank=True, max_length=250, null=True)),
                ('date', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='Uploaded', max_length=50)),
                ('file_size', models.CharField(blank=True, max_length=250, null=True)),
                ('team_name', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='files', to='rest_api.team')),
            ],
            options={
                'db_table': 'api_file',
                'ordering': ['-id'],
            },
        ),
    ]
